dist: xenial
sudo: false
install:
- curl https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz -o emsdk-portable.tar.gz
- tar -xzf emsdk-portable.tar.gz
- emsdk-portable/emsdk update
- emsdk-portable/emsdk install sdk-1.37.28-64bit > emsdk_install.log
- emsdk-portable/emsdk activate sdk-1.37.28-64bit
- source emsdk-tools/emsdk-portable/emsdk_env.sh

- emcc -v
- cat ~/.emscripten

script:
- mkdir -p dist
- emcc src/hello_world.c -o dist/a.out.js
- node dist/a.out.js
- git status
