dist: trusty
sudo: false
cache:
  directories:
  - ~/emscripten_manual_cache
install:
- find ~/emscripten_manual_cache -type f

- mkdir -p emsdk-tools
- cp support/libstdc++6_5.1.0-0ubuntu11~10.04.2_amd64.deb emsdk-tools/
- cd emsdk-tools && ar xv libstdc++6_5.1.0-0ubuntu11~10.04.2_amd64.deb && cd ..
- tar -xzf emsdk-tools/data.tar.gz -C emsdk-tools
- export LD_LIBRARY_PATH=${PWD}/emsdk-tools/usr/lib

- find ~/emscripten_manual_cache -type f

- curl https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz -o emsdk-tools/emsdk-portable.tar.gz
- tar -xzf emsdk-tools/emsdk-portable.tar.gz -C emsdk-tools
- emsdk-tools/emsdk-portable/emsdk update
- emsdk-tools/emsdk-portable/emsdk install sdk-1.37.28-64bit > emsdk-tools/emsdkinstall.log
- emsdk-tools/emsdk-portable/emsdk activate sdk-1.37.28-64bit
- source emsdk-tools/emsdk-portable/emsdk_env.sh

- find ~/emscripten_manual_cache -type f

- emcc --cache ~/emscripten_manual_cache -v 
- cat ~/.emscripten

- find ~/emscripten_manual_cache -type f

script:
- mkdir -p dist
- emcc --cache ~/emscripten_manual_cache -o dist/a.out.js src/hello_world.c 
- node dist/a.out.js
- git status
- find ~/emscripten_manual_cache -type f
