dist: xenial
sudo: false
install:
- git clone https://github.com/juj/emsdk.git
- emsdk/emsdk update-tags
- emsdk/emsdk install sdk-1.39.0-64bit > emsdk_install.log
- emsdk/emsdk activate sdk-1.39.0-64bit
- source emsdk/emsdk_env.sh

- emcc -v
- cat ~/.emscripten

script:
- mkdir -p dist
- emcc src/hello_world.c -o dist/a.out.js
- node dist/a.out.js
- git status
